# Site settings
title: Jaehoon Lee
email: jaehlee@phas.ubc.ca
description: > # this means to ignore newlines until "baseurl:"
  I'm a postdoctoral researcher in the Department of Physics and Astronomy
  at the University of British Columbia.
  I recieved my PhD in theoretical physics at MIT.
  I study theoretical physics and machine learning.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jaehlee.github.io" # the base hostname & protocol for your site
twitter_username: hoonkp
github_username:  jaehlee
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
