# Site settings
title: Jaehoon Lee - Google Brain
email: eejaehoon at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Machine Learing Researcher and Physicist
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jaehlee.github.io" # the base hostname & protocol for your site
twitter_username: hoonkp
github_username:  jaehlee
linkedin_username: eejaehoon
permalink: /blog/ #/cv/research/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
